title: "Jacob Rodgers"
author: "Jacob Rodgers"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  # - {file: "index.html", title: "Home"} # getting rid of Home buttom since my name already does that
  - {file: "cv.html", title: "CV"}
  - {file: "blog.html", title: "Blog"} # coming soon

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rodgerja@oregonstate.edu"}
  # - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/jacobrodgers24/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
